### ISSUE TITLE
Add Grayscale image preprocessor

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/kotlindl#202]
The Grayscale image preprocessor is missed in KotlinDL.
Convert image to grayscale. 
 
The main question is: should we keep the ImageShape with 3 channels or with 1 channel? Or support the difference via parameter like in PyTorch

The desired PR addressing this issue should include:

- [ ]  Implementation (you can take inspiration from the implementation of [`Cropping`][1]  as reference) 
- [ ]  Documentation 
- [ ]  JUnit tests in `dataset` module
- [ ]  An example with usage of this image preprocessor

[1]: https://github.com/JetBrains/KotlinDL/blob/master/dataset/src/main/kotlin/org/jetbrains/kotlinx/dl/dataset/preprocessor/image/Cropping.kt

P.S. If you want to take this ticket, please leave the comment below
P.P.S Read the [Contributing Guidelines](https://github.com/JetBrains/KotlinDL/blob/master/CONTRIBUTING.md).

The reference implementation could be taken from [torchvision.transforms](https://pytorch.org/vision/stable/transforms.html#torchvision.transforms.Grayscale)

**Comment by juliabeliaeva** [comment]
> should we keep the ImageShape with 3 channels or with 1 channel?

Since currently `BufferredImage` is used for image preprocessing, in my PR I use `BufferedImage.TYPE_BYTE_GRAY` and return images with one channel. If we migrate to something else, we could think about supporting 3 channels for grayscale images.
