### ISSUE TITLE
Support export tensor data to image

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/kotlindl#293]
If we have a tensor or FloatArray containing the image data, we should be able to convert this piece of data to the image (BufferedImage at this moment) in Image Preprocessing DSL or in ImageConverter

Look at the `imageToFloatArray` function in ImageConverter. We need `FloatArrayToImage` function.

Also, this function could be added as an Image Preprocessor (analogue of `ImageSaver`) but could be used in the `TensorPreprocessing` DSL block.

**Comment by juliabeliaeva** [comment]
@zaleslaw such function already exists in `examples.dataset.ImagePanelKt#toBufferedImage`, probably could be moved to `ImageConverter`.

**Comment by ermolenkodev** [comment]
Regarding this 
```Also, this function could be added as an Image Preprocessor (analogue of ImageSaver) but could be used in the TensorPreprocessing DSL block.```
Let's move this out to another issue, to speed up release of 0.4
