### ISSUE TITLE
Add Support For Loading Image ByteArray During Preprocessing

### ISSUE THREAD

**Issue by AlexandreBrown** [Kotlin/kotlindl#321]
Currently we are forced to pass in a `File` when loading an image in the preprocess DSL.  
It would be great to support the use case where we already have the images loaded and ready in memory instad of requiring to save them to the disk. This avoids a round trip to the disk and makes it more convenient to the user of the library.

**Comment by zaleslaw** [comment]
Thanks to the issue and proposed PR for this issue, we need to design in this place a better architecture to add new data sources more easily than now. It will be supported in the release 0.4

**Comment by AlexandreBrown** [comment]
@zaleslaw Hello, was this added in 0.4?

**Comment by zaleslaw** [comment]
@AlexandreBrown Unfortunately, it was not included

**Comment by juliabeliaeva** [comment]
Issue became obsolete since the new more flexible preprocessing dsl was implemented in #425. Dataset api also allows to accept different sources now with the `DataLoader` abstraction introduced in #424.
