### ISSUE TITLE
Add export in Keras style for a few new initializers

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/kotlindl#331]
- [ ] Ones
- [ ] Zeros
- [ ] Orthogonal
- [ ] ParametrizedTruncatedNormal

**Comment by zaleslaw** [comment]
@juliabeliaeva could you please have a look at this ticket to start with a Keras-KotlinDL compatibility task

**Comment by juliabeliaeva** [comment]
@zaleslaw ok, I'll work on it.
