### ISSUE TITLE
Generate documentation with Dokka for version 0.4

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/kotlindl#366]
And deploy it with github pages with mutiple version support

**Comment by zaleslaw** [comment]
Nice to hear, could you please share a link here, it will be helpful to check places with missed docs

**Comment by ermolenkodev** [comment]
> Nice to hear, could you please share a link here, it will be helpful to check places with missed docs

sure, here it is - https://ermolenkodev.github.io/KotlinDL/
