### ISSUE TITLE
Running KotlinDL in Docker

### ISSUE THREAD

**Issue by gbaranski** [Kotlin/kotlindl#375]
Hi, have anyone managed to run KotlinDL program in Docker?
I've tried running it, on [tensorflow/tensorflow:1.15.5-gpu](https://hub.docker.com/layers/tensorflow/tensorflow/tensorflow/1.15.5-gpu/images/sha256-7ad742cbb2c77a40d0996ec08345dff54fe25f39428486e5f41c69db04b6d17b?context=explore) image, but it failed with errors:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/tensorflow_native_libraries-1653053743069-0/libtensorflow_jni.so: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory
```

**Comment by juliabeliaeva** [comment]
Hi, it looks similar to the issue described in the [README](https://github.com/Kotlin/kotlindl#fat-jar-issue).

**Comment by zaleslaw** [comment]
Hi, @gbaranski do you remember, is answer helped to you?

**Comment by gbaranski** [comment]
> Hi, @gbaranski do you remember, is answer helped to you?

I got no idea, i eventually migrated out from KotlinDL
