### ISSUE TITLE
Сonsider reinitialization of Input/Output shapes in the case of model file changed

### ISSUE THREAD

**Issue by ermolenkodev** [Kotlin/kotlindl#410]
Interestingly, calling `initInputOutputInfo` twice would not change the shapes, because there are checks to initialize them twice. And we need the check for the input shape because for some models it is set manually before initialization. Perhaps, this is something that should be looked into later.

_Originally posted by @juliabeliaeva in https://github.com/Kotlin/kotlindl/pull/409#discussion_r933657498_

**Comment by juliabeliaeva** [comment]
Fixed by #494, where input data from the model is stored separately from input shape set explicitly.
