### ISSUE TITLE
multiple argument support for the Input in OnnxInferenceModel 's predictRaw and it's sibling

### ISSUE THREAD

**Issue by Reqeique** [Kotlin/kotlindl#417]
was trying to import model with 2 parameter in kDL but apparently doesn't seems to be supported because as in "https://github.com/Kotlin/kotlindl/blob/349d09d1a3817b89c12302a0d373a16b5f7e3fa3/onnx/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/onnx/OnnxInferenceModel.kt" no matter how much argument it needs, it would only emit single input because the 3 deriving function seems to take the first element of `onnxsession.inputName` into `onnxsession.run(()` 
I there any plan to resolve this issue ?

**Comment by ermolenkodev** [comment]
Thanks for reporting an issue. We will consider including the fix in the nearest release.
If you want to implement it by yourself, PR is welcome!
