### ISSUE TITLE
Could not find the artifacts kotlin-deeplearning-api:0.5.1 and kotlin-deeplearning-tensorflow:0.5.1 

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/kotlindl#520]
Hi, I'm trying to upgrade the dataframe examples from KotlinDL version 0.4 to 0.5.1. But something goes wrong.

This is a [PR](https://github.com/Kotlin/dataframe/pull/260) with example where I'm trying to do it

`
Could not determine the dependencies of task ':examples:idea-examples:titanic:distTar'.
> Could not resolve all task dependencies for configuration ':examples:idea-examples:titanic:runtimeClasspath'.
   > Could not resolve org.jetbrains.kotlinx:kotlin-deeplearning-api:0.5.1.
     Required by:
         project :examples:idea-examples:titanic
         project :examples:idea-examples:titanic > org.jetbrains.kotlinx:kotlin-deeplearning-impl:0.5.1 > org.jetbrains.kotlinx:kotlin-deeplearning-impl-jvm:0.5.1
         project :examples:idea-examples:titanic > org.jetbrains.kotlinx:kotlin-deeplearning-dataset:0.5.1 > org.jetbrains.kotlinx:kotlin-deeplearning-dataset-jvm:0.5.1
      > No matching variant of org.jetbrains.kotlinx:kotlin-deeplearning-api:0.5.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'apiElements' capability org.jetbrains.kotlinx:kotlin-deeplearning-api:0.5.1 declares a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'runtimeElements' capability org.jetbrains.kotlinx:kotlin-deeplearning-api:0.5.1 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
   > Could not resolve org.jetbrains.kotlinx:kotlin-deeplearning-tensorflow:0.5.1.
     Required by:
         project :examples:idea-examples:titanic
      > No matching variant of org.jetbrains.kotlinx:kotlin-deeplearning-tensorflow:0.5.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'apiElements' capability org.jetbrains.kotlinx:kotlin-deeplearning-tensorflow:0.5.1 declares a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'runtimeElements' capability org.jetbrains.kotlinx:kotlin-deeplearning-tensorflow:0.5.1 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

`

**Comment by zaleslaw** [comment]
@juliabeliaeva @ermolenkodev please have a look

**Comment by zaleslaw** [comment]
I tried to downgrade it to the previous version (0.5.0) and it didn't work.

**Comment by juferdinand** [comment]
same issue here, I have Project with Java 18 and my Windows have also Java 18

**Comment by juferdinand** [comment]
I found the Problem I think in my build.gradle.kts was this:
kotlin {
    jvmToolchain(8)
}

So Gradle said: U are Java 8 and not Java 11 or higher

After I changed Version the problem was away and the download started. Hopefully it fix your issue too @zaleslaw
