### ISSUE TITLE
Suggestion for improvement: need examples to create time-series predictions

### ISSUE THREAD

**Issue by arstagaev** [Kotlin/kotlindl#527]
Like in here: https://keras.io/examples/timeseries/timeseries_weather_forecasting/ 

kotlindl does have instruments for work with this type of NN? I don't found their.
mostly I am android developer:)

**Comment by zaleslaw** [comment]
At this moment, KotlinDL suffers from the lack of LSTM unit; this unit is not available in the used 1.15 TF Runtime
Another idea could be implementing from scratch a custom LSTM, but it's not a simple thing
