### ISSUE TITLE
Title of plot not fully readable

### ISSUE THREAD

**Issue by b0n541** [Kotlin/kotlindl#530]
When I run the LeNetMnistVisualization from the examples module 

https://github.com/Kotlin/kotlindl/blob/master/examples/src/main/kotlin/examples/visualization/LeNetMnistVisualization.kt

the title of the plot is not fully displayed. One can't read the predicted label:

![image](https://user-images.githubusercontent.com/2326303/230784623-2cf17f98-c99b-4f25-8ba9-dcb994cb5de0.png)

It would be better to introduce a line break instead of the pipe symbol between the real and predicted label.

**Comment by b0n541** [comment]
I would like to fix this issue.

**Comment by b0n541** [comment]
This is how it would look like:

![image](https://user-images.githubusercontent.com/2326303/230788681-0ff6d438-d401-4521-893b-ae3020f60b3d.png)

**Comment by juliabeliaeva** [comment]
@b0n541 looks nice, a PR would be very welcome!
