### ISSUE TITLE
Iheriting the Dataset class

### ISSUE THREAD

**Issue by RawEnchilada** [Kotlin/kotlindl#532]
My question is somewhat related to #529 

I require a custom dataset to train my model with, but i can't find any good explanations for it.

The documentation about Dataset, DataLoader and DataBatch classes are not very clear. I have created a custom dataset class that inherits the original Dataset, but it requires a createDataBatch function to be implemented that returns a DataBatch instance. 
DataBatch doesn't have a public constructor so how can this be achieved?

**Comment by juliabeliaeva** [comment]
@RawEnchilada it seems that this is a bug, sorry about that. There is a workaround though: it looks like the internal constructor can still be referenced from java code. So one idea is that temporarily you can add a java class like so:
```java
public class DataBatchUtil {
    public static DataBatch createBatch(float[][] x, float[] y, int size) {
        return new DataBatch(x, y, size);
    }
}
```
And use this utility class to create new data batches. This is a bit ugly, but should work temporarily.

Other alternative is maybe not implementing a new `DataSet` but reusing available implementations. What is your use case, perhaps it can be implemented without a new class?
