### ISSUE TITLE
Lack of definitions in 5.0, 5.1. 6.0 jars

### ISSUE THREAD

**Issue by rychuelektryk** [Kotlin/kotlindl#535]
Hi,

I don't know, maybe I'm missing something, but 4.0 jar weighs ~850kb and has all the definitions(for example Functional class), while 5.0 or 5.1 weigh only ~50kb and barely have any code at all. 

in my build.gradle.kts i specify dependency as follows
dependencies {
    implementation("org.jetbrains.kotlinx:kotlin-deeplearning-api:0.5.0")
//    implementation("org.jetbrains.kotlinx:kotlin-deeplearning-api:0.4.0") // with 4.0 everythings fine
}

Even if i download your jars from jar-download.com then they also seem corrupted(5.0, 5.1, 6.0 very small without definitions but 4.0 is ok)

How come nobody else have this problem? I'd be gratefull for any support in this matter :)

**Comment by rychuelektryk** [comment]
sorry, i didn't read carefouly enough and missed info about setting dependency to kotlin-deeplearning-tensorflow. Now everything is fine. Feel free to remove this thread.

**Comment by zaleslaw** [comment]
Nice, that you gound a solution
