### ISSUE TITLE
Detect face landmarks with Fan2d106 returns strange landmarks

### ISSUE THREAD

**Issue by lubitelfoto** [Kotlin/kotlindl#541]
`val modelHub = ONNXModelHub(cacheDirectory = File("cache/pretrainedModels"))
    val model = modelHub.loadPretrainedModel(ONNXModels.FaceAlignment.Fan2d106)
    val landmarks = model.detectLandmarks(imageFile = imageFile)`
return
<img width="200" alt="Screenshot 2023-04-20 at 16 08 44" src="https://user-images.githubusercontent.com/15362866/233780249-70daaedc-fbc4-4b08-80ec-41dce89bc9ce.png">

`val modelHub = ONNXModelHub(cacheDirectory = File("cache/pretrainedModels"))
  val model = ONNXModels.PoseDetection.MoveNetSinglePoseLighting.pretrainedModel(modelHub)
    model.use { poseDetectionModel ->
        val detectedPoses = poseDetectionModel.detectPose(imageFile = imageFile)
        var landmarks = mutableListOf<Landmark>()
                detectedPoses.landmarks.forEach { (x,y,_,label) ->
                    if (label=="nose"||label=="left_eye"||label=="right_eye") landmarks.add(Landmark(x,y))
                }`
return

<img width="200" alt="Screenshot 2023-04-22 at 15 03 49" src="https://user-images.githubusercontent.com/15362866/233780386-e5e7207b-1847-4e88-9559-f6a03847f646.png">

Figure get the same method
`landmarks.forEach { (x, y) ->
                    points.add(Offset(this@onDraw.size.width * x , this@onDraw.size.height * y )) }
                drawPoints(points = points,
                    pointMode =  PointMode.Points,
                    color = Color.Red,
                    strokeWidth = 10f
                )`

**Comment by zaleslaw** [comment]
I faced with the same issue earlier, give me a time to have a look into the output

**Comment by juliabeliaeva** [comment]
Fan2d106 model works well only when the face is roughly in the image center and takes a big part of it. In other cases you need to localise the face first. You can do it with the Ultraface face detection model. This is done in the sample Android app (see here https://github.com/Kotlin/kotlindl-app-sample/blob/e82c40e91f1996798639fd0b561c1d2f00800c8a/app/src/main/java/org/jetbrains/kotlinx/dl/example/app/pipelines.kt#L199).

**Comment by lubitelfoto** [comment]
> Fan2d106 model works well only when the face is roughly in the image center and takes a big part of it. In other cases you need to localise the face first. You can do it with the Ultraface face detection model. This is done in the sample Android app (see here https://github.com/Kotlin/kotlindl-app-sample/blob/e82c40e91f1996798639fd0b561c1d2f00800c8a/app/src/main/java/org/jetbrains/kotlinx/dl/example/app/pipelines.kt#L199).
Thank you!
