### ISSUE TITLE
Visualization in example EfficientDetD2LightAPIwithVisualization.kt is broken

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/kotlindl#549]
No rectangles on the image
Output with the negative coordinates instead of relatives.

Need to check twice for these models, probably the whole family of EfficientDet is broken

It looks like the output with negative coordinates for the EfficientDet is not the same like with another types of models like SSD
<img width="1680" alt="Снимок экрана 2023-05-04 в 14 09 09" src="https://user-images.githubusercontent.com/1198621/236200138-3983d6b9-6da0-4bba-b937-f47477942725.png">

**Comment by juliabeliaeva** [comment]
This problem would be fixed by the pr #542.

**Comment by juliabeliaeva** [comment]
Sorry, I was wrong, and #542 does not fix this problem. I submitted a new pr as a fix.

**Comment by juliabeliaeva** [comment]
This problem is not reproduced in the release branch (and the fix is only in master), so I'll remove it from the 0.5.2 milestone.
