### ISSUE TITLE
Support for Tensorflow 2.4

### ISSUE THREAD

**Issue by nicolaiRostrup** [Kotlin/kotlindl#573]
I'm trying to make a project run on GPU Nvidia RTX 3060. It doesn't seem to work with the currently required (old) versions of Tensorflow and CUDA, i.e. TensorFlow 1.5 and CUDA 10.0.
Is it possible to upgrade the support for more recent versions of these to enable use of more modern GPUs?

**Comment by zaleslaw** [comment]
Dear @nicolaiRostrup Unfortunately, no, some reasons are discussed here https://github.com/Kotlin/kotlindl/issues/537
