### ISSUE TITLE
TensorFlow problem:  TensorFlow native library

### ISSUE THREAD

**Issue by invweb** [Kotlin/kotlindl#577]
I connected kotlindl and get an inarticulate error: java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: linux, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
I tried to connect TensorFlow - to no avail, what should I do? Why is this topic not raised in the documentation?

**Comment by invweb** [comment]
![Uploading Screenshot 2023-11-09 at 18.08.00.png…]()

**Comment by invweb** [comment]
![Screenshot 2023-11-09 at 18 08 00](https://github.com/Kotlin/kotlindl/assets/2270351/b204f10c-3442-402a-8953-83b09116bfc8)

**Comment by invweb** [comment]
my test app is here -> https://github.com/invweb/KotlinDL

**Comment by zaleslaw** [comment]
Hi @invweb I learned your case and code, I need to say, that tensorflow model works only on the server side. For Android we support only inference on a few ONNX models.

It tries to load a library compiled for server-side

**Comment by invweb** [comment]
Thanks :))
